=== TN1ck/awesome-MPGI4/TagEditor/Mp3 Sammlung/cache.dtd
<?xml encoding="utf-8"?>
<!ELEMENT cache (folder)>

<!ELEMENT directory (mp3|directory)*>

<!ELEMENT mp3 (frame|song|artist|album|year|cover|tagsize)*>

<!ELEMENT frame (flags|encodingflag|flags|body|pictureType|imageDescription|MIMEType)*>



<!ELEMENT tagsize (#PCDATA)>
<!ELEMENT flags (#PCDATA)>
<!ELEMENT encodingflag (#PCDATA)>
<!ELEMENT body (#PCDATA)>
<!ELEMENT pictureType (#PCDATA)>
<!ELEMENT imageDescription (#PCDATA)>
<!ELEMENT MIMEType (#PCDATA)>

<!ELEMENT song (#PCDATA)>
<!ELEMENT artist (#PCDATA)>
<!ELEMENT album (#PCDATA)>
<!ELEMENT year (#PCDATA)>
<!ELEMENT cover (#PCDATA)>

<!ATTLIST frame ID CDATA #REQUIRED>

<!ATTLIST directory
	id 	ID #IMPLIED
	filename CDATA #REQUIRED
>

<!ATTLIST mp3
	id 	ID #IMPLIED
	filepath CDATA #REQUIRED
>

=== TN1ck/awesome-MPGI4/TagEditor/tests/cache.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE directory SYSTEM "cache.dtd">
<directory filename="tests" id="tests">
  <mp3 filepath="tests/01_What_i_hope Kopie.mp3" id="tests:01_What_i_hope_Kopie.mp3">
    <artist>Pinkleasdfasfdsadf</artist>
    <song>What I Hopeasdfasdfasd</song>
    <album>bansen</album>
    <year>2010</year>
    <tagsize>27209</tagsize>
    <cover>/9j/4RLBRXhpZgAATU0AKgAAAAgABwESAAMAAAABAAEAAAEaAAUAAAABAAAAYgEbAAUAAAABAAAAagEoAAMAAAABAAIAAAExAAIAAAAgAAAAcgEyAAIAAAAUAAAAkodpAAQAAAABAAAAqAAAANQACvyAAAAnEAAK/IAAACcQQWRvYmUgUGhvdG9zaG9wIENTNiAoTWFjaW50b3NoKQAyMDEyOjEyOjA1IDIyOjEyOjAyAAAAAAOgAQADAAAAAQABAACgAgAEAAAAAQAAAPqgAwAEAAAAAQAAAPoAAAAAAAAABgEDAAMAAAABAAYAAAEaAAUAAAABAAABIgEbAAUAAAABAAABKgEoAAMAAAABAAIAAAIBAAQAAAABAAABMgICAAQAAAABAAARhwAAAAAAAABIAAAAAQAAAEgAAAAB/9j/7QAMQWRvYmVfQ00AAf/uAA5BZG9iZQBkgAAAAAH/2wCEAAwICAgJCAwJCQwRCwoLERUPDAwPFRgTExUTExgRDAwMDAwMEQwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwBDQsLDQ4NEA4OEBQODg4UFA4ODg4UEQwMDAwMEREMDAwMDAwRDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDP/AABEIAKAAoAMBIgACEQEDEQH/3QAEAAr/xAE/AAABBQEBAQEBAQAAAAAAAAADAAECBAUGBwgJCgsBAAEFAQEBAQEBAAAAAAAAAAEAAgMEBQYHCAkKCxAAAQQBAwIEAgUHBggFAwwzAQACEQMEIRIxBUFRYRMicYEyBhSRobFCIyQVUsFiMzRygtFDByWSU/Dh8WNzNRaisoMmRJNUZEXCo3Q2F9JV4mXys4TD03Xj80YnlKSFtJXE1OT0pbXF1eX1VmZ2hpamtsbW5vY3R1dnd4eXp7fH1+f3EQACAgECBAQDBAUGBwcGBTUBAAIRAyExEgRBUWFxIhMFMoGRFKGxQiPBUtHwMyRi4XKCkkNTFWNzNPElBhaisoMHJjXC0kSTVKMXZEVVNnRl4vKzhMPTdePzRpSkhbSVxNTk9KW1xdXl9VZmdoaWprbG1ub2JzdHV2d3h5ent8f/2gAMAwEAAhEDEQA/APVUkkklKSSSSUpJJJJSkkkklKSSSSUpJJJJSkkkklKSSSSUpJJJJSkkkklP/9D1VJJJJSkkkklKSSSSUpJJJJSkkkklKSSSSUpJJJJSkkkklKSSSSUpJJJJT//R9VSSSSUpJJJJSkGzLxar6ca26uvIyd32elzgH2bBvt9Gtx32+kz3WbPoIy4r67ZOTifWn6s5GHjuzMtjOpfZ8Zm0b7HUVMrD3WPraypu7fc/d/NJKewGXinJdiC6s5TWCx1AcPUDCdrbHVTv9Pd+eirkOndS6Z0T6oWfWhjz1LIzgy/Kynuax9+RY5uLXVY959PExsS1/wBn9Fv6PBx6rP0dlnqerPpP1ufd1nD6ZfndO6n9vY8Nf04kGm6pjsixlzLcjJddjWVMf6WSz0f0jP5j9Ikp6fFysXMobk4l1eRRZOy6pwex0Ha7bZWXMd7moq4bpP1k6m36tdAt6bg4VdvU8q/EOLW04+OyHZe26prHWentfj+vez9L6/6X0/0li3uldU6n+2cvovVvQffTTXl4+RjNfW19Njn0ObbRdZkOquqvpf8A9qLPVrf/AINJTfzur9J6cWjqGbj4ZfqwX2sqn+r6rmbkZ+ZiV1V3PvrZVcWNqsc9oa91mlLa3k7Xut3fotv84uZ6ra6r69YzmYNnUSelXA01eiHAfaKP0h+23Y1W38z+c9T9Isvp11eB9WH2fZ6H3N6y0u6ZkVl9eA/Ivqb9kxmOFHvxar/Xpvpb6Pq3b6P0SSnt6Oo4WRmZWDTaH5WD6f2qoTLPVb6lO7Tb+kY3cnys/ExH47MmwVuy7RRjgg+6wtdYK9B+5W/6S41vV29G+sv106gaXZL6/wBlsqx2EB1lltRooqDj9Hfdaze79z8x6sdY/wCcLc/6ut6scS1j+oVuL8Vtlfp2ijK3UbL7L/tNTt3syf1b+a/o36VJT2SSSSSlJJJJKUkkkkp//9L1VJJJJSkkkklKWP1Lolub9YejdXba1lfSvtXqVkEl/wBorbQ3Yfzdm1bCSSnmsn6ovsyOp1UZP2fpvVS3Kcxg23UdQrfXYzOxLGbfZb6Nd19dnv8AtFf6Oz9ItHptP1mrvI6plYd+M0Qw0UWV2vP+ksdZk21Vf1GVvWoqPVOsYfS/sf2rd+v5VeFRsG79Lbu9Pf8Aus/R/TSU4fS/qhl4PTOhYT8it7uj5duVa8NcA9thyiG1j8136236S1m9JtH1ms6z6jfRfg14Yqg7tzLbcj1N30dm23atRJJTgdW6P1t/XKOs9Hvxa7GYz8OyvLrse3Y+yvINjPQtpdv/AETVXu+qOTbhZAsy2XdSzs6jNy8o1+mwtx31OpxqKWOseyqjGo9Kr1LrrN/6Sy39IunSSU8xlfU37bl/WGy/JLKuuDE9E1SLKX4bf0du6fd+nbXapW9C+smbk9Ov6l1DGe3puWL210UOrFrAyyn1LzZde77Tts/Rsp9Oirfb/SP0Xo7OB1PGz7MyugO3YN5xrtwgb2truOz95m25quJKUkkkkpSSSSSlJJJJKf/T9VSSSSUpJJJJTgXdXyOmfWXJo6jf/kvIwTmYj37Gtqdinb1Gluxouu3U20Zf6V3s/S+msnpfWPrF1PK6f0i7KODlZeG/rGXdXXW57KLLvSwun4vr1+lW+up/6xZk4+Tat36x/VrE+sFOPXkWPpONbv31aOdW9rqMvEc/6bacvHsfVbsU+r9BGffTnYmVZ03qeM19dOZSGuJrf9PHyaLmvpycfeG2trs/mrv0tXppKec6x1/r3S+l/WHDdlCzM6QzHyMPqIYwWPqyHn9Hk4/puxPXp9Kyj1a69l1f6X7PTYl9acfrNOF0AZ+ZXk59vXsZ7X+ltppLm3bMeqqt1V19GN+a+677Rf8A4SxauR9S8bI6P1LAty7bczq+w5vUbAw2uNe30mitjaqWUV7NlVLP5vetDrXRK+rnp/qWuq/Z2bVnN2gHc6kPip276LX+okpyMXqfU+n/AFizOg9Q6iMmodN/aVOfkV1VGja/7Lcy/wBAY9FtLXD7Tv8A0Wz+b/4RV+l9eyx1rpeNX1DJ6rhdTbYyy7JwzjVh7KrMuvIwchmJiVXVWtpc30fUyf0f6Vly1upfVTD6n1XJ6hk2vAy+mu6XZUyBFb7PtBuZZ7v0v9nYoYv1Yy2ZuDm53VsjqFvTrLHUNtbWxmyyq3F2OZjsq9S7bax32m71f5v9H6XrWpKcb9pfWjI6T1zqzOptoHRcnNbj0Nore26vEe+70857xv8AfS37LX9k+zemz9PZZkXLRo6p1P6wdRZj4GS7peJRh4+ZkvrZXZe+zMbY/Hx6zlVX47aaWVb7rfS9R7/0au1fVmqvpPV+mfaHOb1izLtfYWia/tm7c1jfz/S3oL/qo+sYlvTeo39PzcbFqwbMhja7G3U1QWevjZDLKPWZ+k9K+trH1+tZ/OV+xJTiYPVc/o3TuvW3llvULOtNxWWVVWOYX3MwqGZP2Ss23vd6TvXdi0uf6l36ClaPSOq9VHW8fDNmf1HByqX+vfmYD8Q491QD63tvGLg0vozGusr9F9dltVtX8/8ApFbo+p2DX0/qHT7Mi+2vqOQMw3l+29l4bR+s1317f0/2nG+1s21sq/wXo+irnTOm9VxL7LM3q93Ua3AiqmyqioNBIO5z8amqyyzT970/+CSU8lifWD6yVfVDC+t+Z1AWtY6oZOAyisMtpdd9hscbfbc3Nd6n2j1KrKcX2ej9k/wq9AXOH6mUH6nN+qpyn+k0MH2ra3f7Lm5n839D6TfTWvTgW1dSyc52XdZXkMrY3EeR6VRr3bn0NDdzXXbv0n/qr0kpuJJJJKUkkkkp/9T1VJJJJSkkkklKSSSSUpJJJJSkkkklKSSSSUpJJJJSkkkklKSSSSUpJJJJT//V9VSSQsnJoxKH5OS8VU1Dc97uAElJUlWw+o4Oc3dh3svGv0DPDnVu/wA2xj2IlOTj5HqehY230Xmq3YQdr2/TrfH0Xt3fRSUlSSQ7L6a3tZY9rHODnNBMSGfzjv7G5JSRJCyMnHxajdk2NpqBa0veQ1oL3Cusbnfv2PaxFSUpJVLerdLo+0+tl01/YQw5e6xo9IWDdT68n9F6v+C3/wA4raSlJJKDrqm2Mqc4CyySxp5O36e3+ruSUzSVfO6hhdPo+0ZtzMercGB7zEucYYxv7z3fupU9QwL3sroyK7XWsNlYY4O3MAqf6le36dezJx3b2/6apJTYSQ6cijIa51FjbWse6txaQQH1uNdtZj8+uxux6lbbXTW+217a662lz3uIDWtA3Oe9zva1rWpKZJIJzMUY9eU61raLfT9Oxx2gm0tZQPd/pX2VsYiV2V21strcH12NDmOHBaRua4JKZJJJJKf/1vVVU6qOpO6dkN6Ua257mFuO+4lrGuPt9RxFeR/NfzjWei/1PoK2kkp5K36vddfRsqLMalldFZwm5Ln+qajn+vbbl2YvsvvfmYmZZf8AZbbL8nG/Tf6dP/zX65Scp2HnCu7J+0tdkusdvcLKqK8S2yptLcduT6+O+y2ymuv0vVfZT/O2VLrEklPPWdBzr+lYOEbHMFN1tuRUb3/zb6stlGLXkY1WK99OPkZGL6bPTr9Oij/glm3/AFP61f0+7BuyK7ar8bbYyy+5zXZLsdtVt9n6Pc5j86qq/wDz8j0PWstZb0X1jyLsX6vdUysd5rvow8iyqwcteyp72PH9VzVzmT1nP6Q3Kqvttpsrxcd9FOTYy53rWX9Sc5r8r20/rWPh11VepZ6df6Gr+f8A0NyU6HWOg9Sz7cV1Yq9CtuMDjvusa2l1N9eVkur9OtzM37TRX9m3ZDa/R9H/ALtZKHifVzq/rVnOy3XMGaL8nbc9jbq2My/Tf6NFVPpPfkZGF6+JZffjelhV17/Tr9N9d/1oyc7HY/Dvrx3facCtlDjuySy+2jddmMhrG4uXVd+h9Bn6Rn/ait9no49jpX1uys/qGLhnGY02AtvHqVglzfWbdk4QutrvycWm7G9HazF9T9L/AIH7L6V6Ux6z9VupdQzM6yt1Ax88Ft9by6Xtqoq/Zm7bX7PQ6m2+2z+c/VrP5ak7ov1jPVLs8WUtZ61NzMdl9rWWek69h9T9E70XWYeRU2z+frtvxK/0ddPpfZ43fXG8ZBxKKqX5IutosYXma3DqGN0fDde1oLmfaMbM+3f8J/g/0fvU+mfWzNyGZRvxG2WU4luVVTiuc9zzj234VtDd7Wue++7G9TH2s/wvo/4L1bkpN0Lo3WcG1hy7mWEYNePbcbbLj67Pzseu5lfp0/zj7/Vstfk2ej/R/wBN69Cr6s/WRuDXSc13ry8XuOTYA4llFT76XY+PTZX9qdXffbXb6r6b7PUqv/S2q10z61ZOVkdOqvrpbXnvvYyyqxlxsNTWPYaqcS/J9Gn3XMyL7H2+hbi+nf6H2qhMz63bes34lt+G/Coyhi3XNfsdTNeTb+sh73Na1t9WJhes70a7czJ+zs/SVJKZZPQOrnpNOJTcDdi9Qfk47vWc1zcf1L3Y1FeRbRlbX0491dOx9Ftfp/oN/wDhFUp+qXWaam1tyKopx/s9bWWWVgtLOjMuxq3MZvw6ct3SeoMfbR+lx/tjMmv1L/UVu/615FGD0bLdjB7uqYpyH41U2XusFLMhmJi4wLbn77LPflbLa8b/ALUfz3rVVafrZnW2Y91l2HjYbqc19lznNsY849eLfV6f2TIyNllPr5PrY3retbRh5GT6df8AgUpsP6B1dv1cs6ZR6DLr8rItd+lsArrusvyKPRyRX6n2jGfZju/SU/4Oz/g1Uzfqv9Yc2jJxMi6m6m+q8kvvuh1t9OPUxj6W1bG04+XRbbu/65XQz9LWhs+vub9mfacfHudVi25LjVawMeGV3ZLX077vWt+y+hXi9Qqxqsv0sm279P8Aqv6x0fS+rPvyMnBzTVXm417qQytxixoqxsz1KmWfpP0dWfRXd/wv9dJTR6x0HPzep491LmOxaThlgsusaajjZTczKcyhjLK8p+bjsrq/TPZ6T8Zn+kVOj6tdfY0DJzH3OGC2j1Ksg1u9QYzcS2jfZi32+nZl789mbv8AV9b/ALS/o/0nWpJKeb6T0PrWP1LHyc69j2VVtaG47yytgbSMf7F9ntqssvx/V/W/W+10/p/8B+jXSJJJKf/X9VSSSSUpJJJJSkkkklKSSSSUpJJJJSkkkklKSSSSUpJJJJSkkkklKSSSSU//0PVUkkklKSSSSUpJJJJSkkkklKSSSSUpJJJJSkkkklKSSSSUpJJJJSkkkklP/9n/7RwAUGhvdG9zaG9wIDMuMAA4QklNBCUAAAAAABAAAAAAAAAAAAAAAAAAAAAAOEJJTQQ6AAAAAAD9AAAAEAAAAAEAAAAAAAtwcmludE91dHB1dAAAAAUAAAAAUHN0U2Jvb2wBAAAAAEludGVlbnVtAAAAAEludGUAAAAAQ2xybQAAAA9wcmludFNpeHRlZW5CaXRib29sAAAAAAtwcmludGVyTmFtZVRFWFQAAAANADEAOQAyAC4AMQA2ADgALgAxAC4AMgAyAAAAAAAPcHJpbnRQcm9vZlNldHVwT2JqYwAAAAwAUAByAG8AbwBmACAAUwBlAHQAdQBwAAAAAAAKcHJvb2ZTZXR1cAAAAAEAAAAAQmx0bmVudW0AAAAMYnVpbHRpblByb29mAAAACXByb29mQ01ZSwA4QklNBDsAAAAAAi0AAAAQAAAAAQAAAAAAEnByaW50T3V0cHV0T3B0aW9ucwAAABcAAAAAQ3B0bmJvb2wAAAAAAENsYnJib29sAAAAAABSZ3NNYm9vbAAAAAAAQ3JuQ2Jvb2wAAAAAAENudENib29sAAAAAABMYmxzYm9vbAAAAAAATmd0dmJvb2wAAAAAAEVtbERib29sAAAAAABJbnRyYm9vbAAAAAAAQmNrZ09iamMAAAABAAAAAAAAUkdCQwAAAAMAAAAAUmQgIGRvdWJAb+AAAAAAAAAAAABHcm4gZG91YkBv4AAAAAAAAAAAAEJsICBkb3ViQG/gAAAAAAAAAAAAQnJkVFVudEYjUmx0AAAAAAAAAAAAAAAAQmxkIFVudEYjUmx0AAAAAAAAAAAAAAAAUnNsdFVudEYjUHhsQFIAAAAAAAAAAAAKdmVjdG9yRGF0YWJvb2wBAAAAAFBnUHNlbnVtAAAAAFBnUHMAAAAAUGdQQwAAAABMZWZ0VW50RiNSbHQAAAAAAAAAAAAAAABUb3AgVW50RiNSbHQAAAAAAAAAAAAAAABTY2wgVW50RiNQcmNAWQAAAAAAAAAAABBjcm9wV2hlblByaW50aW5nYm9vbAAAAAAOY3JvcFJlY3RCb3R0b21sb25nAAAAAAAAAAxjcm9wUmVjdExlZnRsb25nAAAAAAAAAA1jcm9wUmVjdFJpZ2h0bG9uZwAAAAAAAAALY3JvcFJlY3RUb3Bsb25nAAAAAAA4QklNA+0AAAAAABAASAAAAAEAAgBIAAAAAQACOEJJTQQmAAAAAAAOAAAAAAAAAAAAAD+AAAA4QklNBA0AAAAAAAQAAAB4OEJJTQQZAAAAAAAEAAAAHjhCSU0D8wAAAAAACQAAAAAAAAAAAQA4QklNJxAAAAAAAAoAAQAAAAAAAAACOEJJTQP1AAAAAABIAC9mZgABAGxmZgAGAAAAAAABAC9mZgABAKGZmgAGAAAAAAABADIAAAABAFoAAAAGAAAAAAABADUAAAABAC0AAAAGAAAAAAABOEJJTQP4AAAAAABwAAD/////////////////////////////A+gAAAAA/////////////////////////////wPoAAAAAP////////////////////////////8D6AAAAAD/////////////////////////////A+gAADhCSU0EAAAAAAAAAgACOEJJTQQCAAAAAAAGAAAAAAAAOEJJTQQwAAAAAAADAQEBADhCSU0ELQAAAAAABgABAAAABThCSU0ECAAAAAAAEAAAAAEAAAJAAAACQAAAAAA4QklNBB4AAAAAAAQAAAAAOEJJTQQaAAAAAANJAAAABgAAAAAAAAAAAAAA+gAAAPoAAAAKAFUAbgB0AGkAdABsAGUAZAAtADEAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAPoAAAD6AAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAEAAAAAAABudWxsAAAAAgAAAAZib3VuZHNPYmpjAAAAAQAAAAAAAFJjdDEAAAAEAAAAAFRvcCBsb25nAAAAAAAAAABMZWZ0bG9uZwAAAAAAAAAAQnRvbWxvbmcAAAD6AAAAAFJnaHRsb25nAAAA+gAAAAZzbGljZXNWbExzAAAAAU9iamMAAAABAAAAAAAFc2xpY2UAAAASAAAAB3NsaWNlSURsb25nAAAAAAAAAAdncm91cElEbG9uZwAAAAAAAAAGb3JpZ2luZW51bQAAAAxFU2xpY2VPcmlnaW4AAAANYXV0b0dlbmVyYXRlZAAAAABUeXBlZW51bQAAAApFU2xpY2VUeXBlAAAAAEltZyAAAAAGYm91bmRzT2JqYwAAAAEAAAAAAABSY3QxAAAABAAAAABUb3AgbG9uZwAAAAAAAAAATGVmdGxvbmcAAAAAAAAAAEJ0b21sb25nAAAA+gAAAABSZ2h0bG9uZwAAAPoAAAADdXJsVEVYVAAAAAEAAAAAAABudWxsVEVYVAAAAAEAAAAAAABNc2dlVEVYVAAAAAEAAAAAAAZhbHRUYWdURVhUAAAAAQAAAAAADmNlbGxUZXh0SXNIVE1MYm9vbAEAAAAIY2VsbFRleHRURVhUAAAAAQAAAAAACWhvcnpBbGlnbmVudW0AAAAPRVNsaWNlSG9yekFsaWduAAAAB2RlZmF1bHQAAAAJdmVydEFsaWduZW51bQAAAA9FU2xpY2VWZXJ0QWxpZ24AAAAHZGVmYXVsdAAAAAtiZ0NvbG9yVHlwZWVudW0AAAARRVNsaWNlQkdDb2xvclR5cGUAAAAATm9uZQAAAAl0b3BPdXRzZXRsb25nAAAAAAAAAApsZWZ0T3V0c2V0bG9uZwAAAAAAAAAMYm90dG9tT3V0c2V0bG9uZwAAAAAAAAALcmlnaHRPdXRzZXRsb25nAAAAAAA4QklNBCgAAAAAAAwAAAACP/AAAAAAAAA4QklNBBQAAAAAAAQAAAAFOEJJTQQMAAAAABGjAAAAAQAAAKAAAACgAAAB4AABLAAAABGHABgAAf/Y/+0ADEFkb2JlX0NNAAH/7gAOQWRvYmUAZIAAAAAB/9sAhAAMCAgICQgMCQkMEQsKCxEVDwwMDxUYExMVExMYEQwMDAwMDBEMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMAQ0LCw0ODRAODhAUDg4OFBQODg4OFBEMDAwMDBERDAwMDAwMEQw
